### ISSUE TITLE
Save/Load

### ISSUE THREAD

**Issue by sethandroo** [AsayuGit/HarryPotter2-NeoLauncher#1] opened 2021-04-24 03:48 UTC
I save in the game, but when I open the launcher all the save slots are blank :(

**Comment by AsayuGit** [comment] 2021-04-24 12:32
Thanks for reporting the issue, I was able to reproduce the bug so a fix is being worked on

**Comment by AsayuGit** [comment] 2021-04-24 13:24
@blusterygay Hey the bug was due to a small regression in the latest commit, it's fixed in the latest release, check it out at https://github.com/AsayuGit/HarryPotter2-NeoLauncher/releases/tag/v1.2

**Closed as completed** 2021-04-26 09:56 UTC
Labels: bug
